server:
  port: 8083
  
spring:
  application:
    name: API-GATEWAY
    
    
  cloud:
    gateway:
      routes:
      - id: COLLEGE-SERVICE
        uri:
          lb://COLLEGE-SERVICE
        predicates:
        - Path=/college/**
        
      - id: STUDENT-SERVICE
        uri:
          lb://STUDENT-SERVICE
        predicates:
        - Path=/student/**